<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-06-06T04:05:14Z" name="Surefire suite" finished-at="2018-06-06T04:05:14Z" duration-ms="18">
    <groups>
    </groups>
    <test started-at="2018-06-06T04:05:14Z" name="Surefire test" finished-at="2018-06-06T04:05:14Z" duration-ms="18">
      <class name="TestCase">
        <test-method signature="test()[pri:0, instance:TestCase@4b14c583]" started-at="2018-06-06T11:05:14Z" name="test" finished-at="2018-06-06T11:05:14Z" duration-ms="5"
                     status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Error message from test]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException:
      Error message from test
      at TestCase.test(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- TestCase -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
